# Fundamental concepts of tensors using TensorFlow
contents:
1.   Introduction to tensors
2.   Getting info from tensors
3.   Manipulating tensors
4.   Tensors & NumPy
5.   Using @tf.function (a way to speed up your regular Python functions)
6.   Using GPUs with TensorFlow(or TPU)
7.   Exercises to try for yourself!!





# Introduction to Tensors

In [3]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.12.0


In [4]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [6]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
# Check the dimension of our vector
vector.ndim

1

In [9]:
# Create a matrix (has more then 1 dimension)
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [10]:
# Check Dimension of our matrix
matrix.ndim

2

In [12]:
# create another matrix
another_matrix = tf.constant([[11., 1.],
                              [3., 2.],
                              [5., 6.]], dtype=tf.float16) # specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[11.,  1.],
       [ 3.,  2.],
       [ 5.,  6.]], dtype=float16)>

In [13]:
# No. of dimensions of another matrix
another_matrix.ndim

2

In [14]:
#let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                       [[7, 8, 9],
                        [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [15]:
tensor.ndim

3

What we've created so far:
* Scalar: a single number
* Vector: a number with direction
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers(when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

# Creating tensors with tf.variable

In [16]:
# Create the same tensor with tf.Variable () as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [17]:
# Let's try change one of the elements in our changeable tensor
# using .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [18]:
# Let's try change on our unchangable tensor
unchangeable_tensor[0].assign(7)

AttributeError: ignored

### Creating random tensors

Random tensors are tensors of some abitrary size which contain ranodm numbers.

In [22]:
from tensorflow._api.v2 import random
# Create two random (but the same) tenosrs
random_1 = tf.random.Generator.from_seed(11) #set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(11)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [32]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't effect learning)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
# Shuffles our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [33]:
# Shuffles our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [3]:
import tensorflow as tf
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])

In [7]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [8]:
# other ways to make tensors
#create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [9]:
# Create a tensors of all zeroes
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [15]:
#Create NumPy array and convert to tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) #create a NumPy array between 1 to 24
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [16]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)
C = tf.constant(numpy_A, shape=(8, 3))
A, B, C

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(8, 3), dtype=int32, numpy=
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]], dtype=int32)>)

## Getting information from tensors
When dealing with tensors you probably want to be aware of the following attributes:
* Shape
* Rank
* Axix or dimension
* Size

In [17]:
# Create a rank 4 tensor ( 4 Dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [18]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [19]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [20]:
# Get various atrributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of Dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in out tensor:", tf.size(rank_4_tensor))
print("toatal number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of Dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in out tensor: tf.Tensor(120, shape=(), dtype=int32)
toatal number of elements in our tensor: 120


## indexing tensor
Tensors can be indexed just like python lists.

In [21]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2. :2, :2/wohtpumtysvles do dolo
              ]

SyntaxError: ignored

In [1]:
import tensorflow as tf
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [2]:
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [4]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                            [3, 4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [5]:
some_list = tf.constant([1, 2, 3, 4])

In [6]:
some_list, some_list[-1]

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [9]:
# Get the last item of each row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [10]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [12]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [13]:
tf.expand_dims(rank_2_tensor, axis=0) # expand the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [14]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

### Manipulating tensors (tensor operations)

**Basic operations**
+, -, *, /

In [15]:
# you can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], 
                      [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [16]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [17]:
# Multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [18]:
# Subtraction
tensor - 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[8, 5],
       [1, 2]], dtype=int32)>

In [19]:
# TensorFlow build-in fucntion
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**Matrix multiplication**

In machine learning, Matrix multiplication is one of the most comman tensor operations.

In [22]:
# Matrix multiplication in TensorFlow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [23]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [24]:
# Matrix multiplication with python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [25]:
tensor.shape

TensorShape([2, 2])

In [29]:
# Create a tensor (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Try to matrix multiply tensor of same shape

In [30]:
# Let's change the shape of Y
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [31]:
# Multiply X with reshaped Y
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [32]:
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [33]:
# Change shape of X in place of Y
tf.matmul(tf.reshape(X, shape=(2, 3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [34]:
# Can do the same with transpose
X, tf.transpose(X)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>)

**The dot product**

Matrix multiplication is also referrred to as the dot product.

You can perform matrix multiplication using:

* tf.matmul()
* tf.tensordot()

In [35]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [36]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [37]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [38]:
# Check the values of Y, reshape Y and transposed Y
print("Normal Y:")
print(Y, "\n") # "\n" for new line

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))



Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [39]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

Generally, when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose (rather than reshape) one of the tensors to satisfy the matrix multiplication rule.

### Changeing the datatype of a tensor

In [44]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [41]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [43]:
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [46]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [47]:
E_float16 = tf.cast(E, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

### Aggregating tesnors

Aggregating tensor = Considering them from multiple values down to a smalller amount of values.

In [48]:
# get the absolute calues
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [49]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the folllowing forms of aggregation:
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor|

In [51]:
# Create a random tensor with values between 0 and 100 of size 50
import numpy as np
E =  tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([35, 98, 41, 16, 33, 68,  4, 26, 82, 63,  6, 15, 92, 29, 26, 74, 35,
       67, 20, 29, 61, 27, 71, 47, 78,  1, 98, 64, 48, 93, 48,  6, 12, 72,
       91, 58, 61, 29, 63, 96, 48, 64, 42, 66,  2,  2, 64, 26,  0, 60])>

In [52]:
tf.size(E), E.shape, E.ndim


(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [53]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [54]:
# Find the maximimum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [55]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [56]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2357>

In [72]:
# Find the Variance
import tensorflow_probability as tfp
np.var(E)
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=836>

In [75]:
# Find the Standard Deviation
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.922663>

In [77]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=836.5204>

### Find the positional maximum and minimum



In [78]:
# create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [79]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [80]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [81]:
# Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [85]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [86]:
# Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [87]:
# Find the minimum using the positional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (removing all single dimensions)

In [88]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [89]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [90]:
# Squeezing removes all single dimensions from tensor
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One-hot encoding tensors

In [91]:
# Create a list of indices
some_list = [0, 1, 2, 3] # could be red, green, blue, purple

# One hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [92]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="I love TF", off_value="I also love Flutter")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I love TF', b'I also love Flutter', b'I also love Flutter',
        b'I also love Flutter'],
       [b'I also love Flutter', b'I love TF', b'I also love Flutter',
        b'I also love Flutter'],
       [b'I also love Flutter', b'I also love Flutter', b'I love TF',
        b'I also love Flutter'],
       [b'I also love Flutter', b'I also love Flutter',
        b'I also love Flutter', b'I love TF']], dtype=object)>

### Squaring, log, square root

In [93]:
# Create a new tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [95]:
# Sqaure it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [96]:
# Find the square root.
tf.math.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [99]:
# Find the log
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### TensorFlow and NumPy
Tensorflow interacts beautifully with NumPy array

In [100]:
# Create a tensor directly from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [101]:
# Convert our tensor back to a NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [102]:
# Convert tensor J to a NumPy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [104]:
# The dfault types of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])
# Check the datatype of each 
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUs


In [1]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [4]:
!nvidia-smi

Fri May  5 07:11:11 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8     9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

**Note**: If you have access to a CUDA-enabled GPU, TensorFlow will automatically use it whenever possible.

# Exercises

In [9]:
scalar = tf.constant(2)
scalar, scalar.shape, scalar.ndim, tf.size(scalar)

(<tf.Tensor: shape=(), dtype=int32, numpy=2>,
 TensorShape([]),
 0,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [10]:
vector = tf.constant([1., 2., 3.])
vector, vector.shape, vector.ndim, tf.size(vector)

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>,
 TensorShape([3]),
 1,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>)

In [11]:
matrix = tf.constant([[4., 5., 6],
                      [7., 8., 9]])
matrix, matrix.shape, matrix.ndim, tf.size(matrix)

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[4., 5., 6.],
        [7., 8., 9.]], dtype=float32)>,
 TensorShape([2, 3]),
 2,
 <tf.Tensor: shape=(), dtype=int32, numpy=6>)

In [15]:
tensor = tf.constant([[[10, 11, 12],
                      [13, 14, 15]], 
                     [[16, 17, 18],
                     [19, 20, 21]]])
tensor, tensor.shape, tensor.ndim, tf.size(tensor)

(<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[10, 11, 12],
         [13, 14, 15]],
 
        [[16, 17, 18],
         [19, 20, 21]]], dtype=int32)>,
 TensorShape([2, 2, 3]),
 3,
 <tf.Tensor: shape=(), dtype=int32, numpy=12>)

In [19]:
First_01_tensor = tf.random.Generator.from_seed(42)
First_01_tensor = First_01_tensor.normal(shape=(5, 300))
Second_01_tensor = tf.random.Generator.from_seed(41)
Second_01_tensor = Second_01_tensor.normal(shape=(5, 300))
First_01_tensor, Second_01_tensor

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, ..., -1.0718341 ,
         -1.0722276 , -0.00586287],
        [-0.88051033, -0.32426047, -2.4847078 , ...,  0.16512105,
          1.155565  , -0.10707551],
        [-1.5306779 , -0.8620293 , -0.16359143, ...,  0.34288087,
          1.2167931 , -1.24293   ],
        [ 0.84324265, -0.23379943,  0.4276398 , ..., -1.0428714 ,
         -0.73970354,  0.0177109 ],
        [ 0.04888754, -0.66408694, -1.787366  , ...,  0.1947453 ,
          0.5656089 ,  0.18439198]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[ 0.31662667, -1.4391748 ,  0.58923835, ..., -0.2818856 ,
         -1.2894468 ,  0.96435696],
        [-0.60367185, -1.0718341 , -1.0722276 , ..., -1.7472465 ,
         -0.26269418,  0.3709909 ],
        [ 0.05165245,  0.16512105,  1.155565  , ..., -0.16120234,
          1.0154027 ,  0.52378887],
        [ 0.98307234,  0.34288087,  1.2167931 , ..., -1.8173325 

In [24]:
Mul_First_Second_tensor = tf.matmul(First_01_tensor, tf.transpose(Second_01_tensor))
Mul_First_Second_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 23.434526  , -27.73486   ,  17.023205  ,   0.89414287,
         28.74288   ],
       [ 27.64816   ,  41.60547   ,   4.7097516 , -17.55016   ,
        -14.712549  ],
       [-15.495375  , -27.314936  ,  11.772947  ,  -3.8316598 ,
        -37.46029   ],
       [-16.17693   ,  -5.9228864 ,  35.46706   ,  10.984352  ,
        -11.6045475 ],
       [  1.1972945 ,  40.336613  , -20.134008  ,  20.396168  ,
         12.943839  ]], dtype=float32)>

In [27]:
Dot_First_Second_tensor = tf.tensordot(First_01_tensor, tf.transpose(Second_01_tensor), axes=1)
Dot_First_Second_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 23.434526  , -27.73486   ,  17.023205  ,   0.89414287,
         28.74288   ],
       [ 27.64816   ,  41.60547   ,   4.7097516 , -17.55016   ,
        -14.712549  ],
       [-15.495375  , -27.314936  ,  11.772947  ,  -3.8316598 ,
        -37.46029   ],
       [-16.17693   ,  -5.9228864 ,  35.46706   ,  10.984352  ,
        -11.6045475 ],
       [  1.1972945 ,  40.336613  , -20.134008  ,  20.396168  ,
         12.943839  ]], dtype=float32)>

In [29]:
tensor_01_3d = tf.random.Generator.from_seed(40)
tensor_01_3d = tensor_01_3d.normal(shape=(224, 224, 3))
tensor_01_3d

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[ 7.89536238e-01,  5.38973451e-01, -4.85357106e-01],
        [ 7.40552723e-01,  3.16626668e-01, -1.43917477e+00],
        [ 5.89238346e-01, -1.42680454e+00, -7.56580293e-01],
        ...,
        [ 9.87372339e-01,  6.40017748e-01, -1.20539911e-01],
        [-1.22489989e+00, -6.17037773e-01, -6.33525133e-01],
        [ 5.73403180e-01, -2.02983409e-01,  7.09911436e-02]],

       [[-5.09576797e-01,  3.48200113e-01,  1.59859821e-01],
        [-1.90421844e+00,  9.69050407e-01,  1.62511855e-01],
        [-7.33075142e-02, -3.60590965e-01,  1.87394410e-01],
        ...,
        [ 9.01131809e-01, -1.57612646e+00, -4.13054138e-01],
        [-3.66801620e-01, -1.12992600e-02,  1.62802827e+00],
        [ 5.46300948e-01,  1.74018586e+00, -1.94602954e+00]],

       [[-7.97727525e-01,  3.09283305e-02,  8.29748809e-01],
        [ 1.21791191e-01,  1.05061078e+00, -1.30976379e+00],
        [ 9.25369740e-01, -1.17877316e+00, -2.17118248e-01],


In [30]:
tf.reduce_min(tensor_01_3d, axis=1)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[-3.3228776, -3.1925747, -2.3410842],
       [-2.5273206, -2.447787 , -3.5026186],
       [-2.4798658, -3.3332396, -2.3067753],
       [-2.4179578, -2.0617082, -2.2954667],
       [-3.7600887, -2.6800404, -2.326195 ],
       [-2.2611363, -3.1665409, -2.5137002],
       [-2.802091 , -3.1299603, -2.3334813],
       [-2.7199616, -2.2556791, -2.844876 ],
       [-2.6013858, -2.3679602, -2.508281 ],
       [-2.6478539, -3.4689443, -2.721599 ],
       [-3.0635452, -3.5580223, -2.6412008],
       [-2.072052 , -2.809761 , -2.4719346],
       [-3.484727 , -2.3191102, -2.436559 ],
       [-2.4216607, -3.5306044, -2.9851797],
       [-3.097142 , -2.810968 , -2.6066418],
       [-2.3063118, -2.6547732, -2.5699522],
       [-2.6061351, -3.2508569, -3.4615564],
       [-2.7427094, -2.646806 , -3.0765069],
       [-1.9347261, -2.413212 , -2.4228384],
       [-2.5334885, -2.448361 , -3.094437 ],
       [-2.4752731, -2.028599 , -3.5121346],
     

In [31]:
tf.reduce_max(tensor_01_3d, axis=1)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[2.4963074, 2.6791053, 2.6145976],
       [3.125233 , 2.6236527, 2.9900203],
       [2.4381642, 2.0650482, 2.5721583],
       [3.2582695, 3.3247573, 2.7856476],
       [2.3420217, 2.808597 , 3.0055242],
       [3.1547995, 2.8823073, 2.999433 ],
       [2.5854058, 2.1346638, 2.2318754],
       [2.9041176, 2.8385136, 2.9206035],
       [2.5296538, 2.6940217, 2.4433494],
       [2.6298215, 2.4473062, 2.5206945],
       [2.8681247, 3.0223954, 2.7422664],
       [2.8307083, 2.2926984, 2.5306084],
       [2.8050215, 2.8158236, 2.6012046],
       [2.4175484, 2.505006 , 2.3072338],
       [3.0322127, 2.276533 , 3.2084305],
       [2.9356906, 2.913884 , 2.9325006],
       [2.8860726, 2.7476034, 2.7453153],
       [2.0602324, 2.56912  , 2.5614219],
       [2.5316076, 2.306367 , 3.081714 ],
       [2.5930557, 3.1296818, 3.1423316],
       [3.0813627, 2.9003572, 2.6985295],
       [2.5066452, 2.6691477, 2.7967956],
       [2.4238677, 2.68073

In [33]:
random_tensor = tf.random.Generator.from_seed(39)
random_tensor = random_tensor.normal(shape=(1, 224, 224, 3))
random_tensor

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[ 8.14849973e-01,  1.27906656e+00,  2.20350940e-02],
         [ 1.54281211e+00,  7.89536238e-01,  5.38973451e-01],
         [-4.85357106e-01,  7.40552723e-01,  3.16626668e-01],
         ...,
         [ 1.64008081e+00, -9.76320982e-01, -1.16807461e+00],
         [-2.49750093e-01,  9.87372339e-01,  6.40017748e-01],
         [-1.20539911e-01, -1.22489989e+00, -6.17037773e-01]],

        [[-6.33525133e-01,  5.73403180e-01, -2.02983409e-01],
         [ 7.09911436e-02, -5.09576797e-01,  3.48200113e-01],
         [ 1.59859821e-01, -1.90421844e+00,  9.69050407e-01],
         ...,
         [-1.26423791e-01,  6.32863462e-01,  2.48639695e-02],
         [ 3.24882329e-01,  9.01131809e-01, -1.57612646e+00],
         [-4.13054138e-01, -3.66801620e-01, -1.12992600e-02]],

        [[ 1.62802827e+00,  5.46300948e-01,  1.74018586e+00],
         [-1.94602954e+00, -7.97727525e-01,  3.09283305e-02],
         [ 8.29748809e-01,  1.21791191e-01

In [34]:
squeezed_tensor = tf.squeeze(random_tensor)
squeezed_tensor.shape

TensorShape([224, 224, 3])

In [35]:
my_tensor = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_tensor.shape

TensorShape([10])

In [38]:
tf.argmax(my_tensor), tf.argmin(my_tensor)

(<tf.Tensor: shape=(), dtype=int64, numpy=9>,
 <tf.Tensor: shape=(), dtype=int64, numpy=0>)

In [42]:
tf.one_hot(my_tensor, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

# Congratulations!! to self