In [1]:
import tensorflow as tf

In [3]:

# Import with pandas
import pandas as pd
# Parse dates and set date column to index
df = pd.read_csv("/content/train.csv",
                 parse_dates=["id"],
                 index_col=["id"]) # parse the id column (tell pandas column 1 is a id)
df.head()

CementComponent  BlastFurnaceSlag  FlyAshComponent  WaterComponent  \
id                                                                       
0             525.0               0.0              0.0           186.0   
1             143.0             169.0            143.0           191.0   
2             289.0             134.7              0.0           185.7   
3             304.0              76.0              0.0           228.0   
4             157.0             236.0              0.0           192.0   

    SuperplasticizerComponent  CoarseAggregateComponent  \
id                                                        
0                         0.0                    1125.0   
1                         8.0                     967.0   
2                         0.0                    1075.0   
3                         0.0                     932.0   
4                         0.0                     935.4   

    FineAggregateComponent  AgeInDays  Strength  
id                                               
0                    613.0          3     10.38  
1                    643.0         28     23.52  
2                    795.3         28     36.96  
3                    670.0        365     39.05  
4                    781.2         90     74.19

In [4]:
test_df = pd.read_csv("/content/test.csv",
                 parse_dates=["id"],
                 index_col=["id"]) # parse the id column (tell pandas column 1 is a id)
test_df.head()

CementComponent  BlastFurnaceSlag  FlyAshComponent  WaterComponent  \
id                                                                         
5407            166.1              75.4            163.8           173.8   
5408            304.0               0.0              0.0           190.0   
5409            225.0               0.0              0.0           185.0   
5410            251.4               0.0            118.3           188.5   
5411            144.0              15.0            195.0           176.0   

      SuperplasticizerComponent  CoarseAggregateComponent  \
id                                                          
5407                        4.6                    1007.2   
5408                        0.0                     998.0   
5409                        0.0                    1113.0   
5410                        6.4                    1028.4   
5411                        6.0                    1021.0   

      FineAggregateComponent  AgeInDays  
id                                       
5407                   746.6         56  
5408                   801.0          7  
5409                   833.0         28  
5410                   757.7        100  
5411                   709.0         28

In [5]:
test_df = pd.read_csv("/content/sample_submission.csv",
                 parse_dates=["id"],
                 index_col=["id"]) # parse the id column (tell pandas column 1 is a id)
test_df.head()

Strength
id            
5407    35.452
5408    35.452
5409    35.452
5410    35.452
5411    35.452

In [6]:
#Create X and Y values
X = df.drop("Strength", axis=1)
Y = df["Strength"]

In [7]:
X.head()

CementComponent  BlastFurnaceSlag  FlyAshComponent  WaterComponent  \
id                                                                       
0             525.0               0.0              0.0           186.0   
1             143.0             169.0            143.0           191.0   
2             289.0             134.7              0.0           185.7   
3             304.0              76.0              0.0           228.0   
4             157.0             236.0              0.0           192.0   

    SuperplasticizerComponent  CoarseAggregateComponent  \
id                                                        
0                         0.0                    1125.0   
1                         8.0                     967.0   
2                         0.0                    1075.0   
3                         0.0                     932.0   
4                         0.0                     935.4   

    FineAggregateComponent  AgeInDays  
id                                     
0                    613.0          3  
1                    643.0         28  
2                    795.3         28  
3                    670.0        365  
4                    781.2         90

In [8]:
# Create training and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    Y,
                                                    test_size=0.2,
                                                    random_state=42) # set random state for reproducible splits

In [ ]:
# Set random seed
tf.random.set_seed(42)

# Create a new model (same as model_2)
model_00 = tf.keras.Sequential([
  tf.keras.layers.Dense(1),
  tf.keras.layers.Dense(1)
])

# Compile the model
model_00.compile(loss=tf.keras.losses.mae,
                        optimizer=tf.keras.optimizers.SGD(learning_rate = 0.001),
                        metrics=['mse'])

# Fit the model
model_00.fit(X_train, y_train, epochs=100)

Epoch 1/100
136/136 [==============================] - 2s 7ms/step - loss: 36.2708 - mse: 5489.0498
Epoch 2/100
136/136 [==============================] - 1s 7ms/step - loss: 26.0001 - mse: 966.0917
Epoch 3/100
136/136 [==============================] - 1s 5ms/step - loss: 25.3628 - mse: 926.6472
Epoch 4/100
136/136 [==============================] - 1s 7ms/step - loss: 26.8126 - mse: 1010.8967
Epoch 5/100
136/136 [==============================] - 1s 6ms/step - loss: 26.6222 - mse: 1055.0453
Epoch 6/100
136/136 [==============================] - 1s 6ms/step - loss: 26.0949 - mse: 987.0712
Epoch 7/100
136/136 [==============================] - 1s 8ms/step - loss: 25.2369 - mse: 920.3462
Epoch 8/100
136/136 [==============================] - 1s 7ms/step - loss: 24.7577 - mse: 913.1290
Epoch 9/100
136/136 [==============================] - 1s 4ms/step - loss: 26.8459 - mse: 1011.0859
Epoch 10/100
136/136 [==============================] - 2s 13ms/step - loss: 25.2022 - mse: 897.0596
Epoc

In [ ]:
# Evaluate model_00
model_00_result = model_00.evaluate(X_test, y_test)
model_00_result

34/34 [==============================] - 0s 2ms/step - loss: 22.6816 - mse: 762.2664


[22.681615829467773, 762.2664184570312]

In [ ]:

# Set random seed
tf.random.set_seed(42)

# Build the model (3 layers, 100, 10, 1 units)
model_01 = tf.keras.Sequential([
  tf.keras.layers.Dense(100),
  tf.keras.layers.Dense(10),
  tf.keras.layers.Dense(1)
])

# Compile the model
model_01.compile(loss=tf.keras.losses.mae,
                          optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
                          metrics=['mse'])

# Fit the model for 200 epochs (same as insurance_model_2)
model_01.fit(X_train, y_train, epochs=200, verbose=0)

In [ ]:
# Evaluate model_01
model_01_result = model_01.evaluate(X_test, y_test)
model_01_result

In [9]:
def build_model(hp):
    model = tf.keras.Sequential([
        tf.keras.layers.Dense(units=hp.Int('units', min_value=32, max_value=512, step=32),
                              activation='relu'),
        tf.keras.layers.Dropout(rate=hp.Float('dropout', min_value=0.0, max_value=0.5, step=0.1)),
        tf.keras.layers.Dense(1)
    ])
    model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=hp.Choice('learning_rate', values=[1e-2, 1e-3, 1e-4])),
                  loss='mae',
                  metrics=['mse'])
    return model


In [10]:
pip install -q -U keras-tuner


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.9/128.9 kB 2.8 MB/s eta 0:00:00


In [11]:
import keras
import keras_tuner as kt

In [ ]:
tuner = kt.RandomSearch(
    build_model,
    objective='val_mse',
    max_trials=10,
    directory='hyperparameter_tuning03',
    project_name='my_project'
)

tuner.search(X_train, y_train, epochs=10, validation_data=(X_train, y_train))

Trial 10 Complete [00h 00m 22s]
val_mse: 154.7992401123047

Best val_mse So Far: 154.1584014892578
Total elapsed time: 00h 03m 14s


In [ ]:
best_hps = tuner.get_best_hyperparameters(num_trials=1)[0]

In [ ]:
best_hps

In [ ]:
model_04 = tuner.hypermodel.build(best_hps)
model_04.fit(X_train, y_train, epochs=100, validation_data=(X_test, y_test))

Epoch 1/100
136/136 [==============================] - 1s 4ms/step - loss: 33.4764 - mse: 4427.9492 - val_loss: 13.2149 - val_mse: 254.5157
Epoch 2/100
136/136 [==============================] - 0s 3ms/step - loss: 11.6433 - mse: 226.1214 - val_loss: 12.4814 - val_mse: 266.2573
Epoch 3/100
136/136 [==============================] - 0s 3ms/step - loss: 11.1410 - mse: 208.9695 - val_loss: 10.6105 - val_mse: 174.2996
Epoch 4/100
136/136 [==============================] - 0s 3ms/step - loss: 11.3253 - mse: 214.0761 - val_loss: 9.9898 - val_mse: 162.6671
Epoch 5/100
136/136 [==============================] - 0s 3ms/step - loss: 10.9022 - mse: 201.2284 - val_loss: 9.8161 - val_mse: 157.9754
Epoch 6/100
136/136 [==============================] - 0s 3ms/step - loss: 10.7243 - mse: 196.2450 - val_loss: 9.6843 - val_mse: 152.1331
Epoch 7/100
136/136 [==============================] - 0s 3ms/step - loss: 11.2549 - mse: 213.8317 - val_loss: 11.6973 - val_mse: 212.8153
Epoch 8/100
136/136 [========

In [ ]:
# Evaluate Model_02
model_02_result = model_02.evaluate(X_test, y_test)

34/34 [==============================] - 0s 2ms/step - loss: 9.5681 - mse: 150.5024


In [ ]:
# Set random seed
tf.random.set_seed(42)

# Build the model (4 layers, 100, 100, 10, 1 units)
model_03 = tf.keras.Sequential([
  tf.keras.layers.Dense(100),
  tf.keras.layers.Dense(100),
  tf.keras.layers.Dense(10),
  tf.keras.layers.Dense(1)
])

# Compile the model
model_03.compile(loss=tf.keras.losses.mae,
                          optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
                          metrics=['mse'])

# Fit the model for 200 epochs (same as insurance_model_2)
model_03.fit(X_train, y_train, epochs=200, verbose=0)

In [ ]:
# Evaluate Model_03
model_03_result = model_03.evaluate(X_test, y_test)

34/34 [==============================] - 0s 2ms/step - loss: 11.3621 - mse: 206.9873


In [ ]:
model_04 = tuner.hypermodel.build(best_hps)
model_04.fit(X_train, y_train, epochs=100, validation_data=(X_test, y_test))

Epoch 1/100
136/136 [==============================] - 2s 5ms/step - loss: 16.0662 - mse: 770.5317 - val_loss: 12.6566 - val_mse: 238.9158
Epoch 2/100
136/136 [==============================] - 1s 5ms/step - loss: 11.9142 - mse: 236.4211 - val_loss: 13.5019 - val_mse: 305.4286
Epoch 3/100
136/136 [==============================] - 1s 4ms/step - loss: 11.2531 - mse: 213.2973 - val_loss: 9.7688 - val_mse: 166.6425
Epoch 4/100
136/136 [==============================] - 1s 4ms/step - loss: 10.4302 - mse: 186.5024 - val_loss: 9.5824 - val_mse: 160.1675
Epoch 5/100
136/136 [==============================] - 1s 9ms/step - loss: 10.0023 - mse: 173.3811 - val_loss: 10.1738 - val_mse: 161.5975
Epoch 6/100
136/136 [==============================] - 1s 8ms/step - loss: 10.1668 - mse: 177.8362 - val_loss: 9.2963 - val_mse: 149.4491
Epoch 7/100
136/136 [==============================] - 1s 8ms/step - loss: 10.1877 - mse: 176.1848 - val_loss: 9.9397 - val_mse: 157.7449
Epoch 8/100
136/136 [==========

In [ ]:
# Evaluate Model_04
model_04_result = model_04.evaluate(X_test, y_test)

34/34 [==============================] - 0s 2ms/step - loss: 9.7519 - mse: 154.3234


In [ ]:
#Using Lasso
from sklearn.linear_model import Lasso

model_05 = Lasso(alpha=1.0)
model_05.fit(X_train, y_train)

Lasso()

In [ ]:
model_05_history = model_05.predict(X_test)

In [ ]:
model_05_history[:5]


array([26.23420089, 30.15608952, 40.12763448, 36.58390576, 33.1349857 ])

In [ ]:
y_test[:5]

id
4269    32.40
1615    18.20
1924    44.52
230     22.93
465     21.50
Name: Strength, dtype: float64

In [ ]:
#predict best model
predict_x_test = model_02.predict(test_df)

113/113 [==============================] - 0s 1ms/step


In [ ]:
predict_x_test[:5]

array([[44.296204],
       [21.586994],
       [32.879562],
       [46.112442],
       [31.608864]], dtype=float32)

In [ ]:
test_df[:5]

CementComponent  BlastFurnaceSlag  FlyAshComponent  WaterComponent  \
id                                                                         
5407            166.1              75.4            163.8           173.8   
5408            304.0               0.0              0.0           190.0   
5409            225.0               0.0              0.0           185.0   
5410            251.4               0.0            118.3           188.5   
5411            144.0              15.0            195.0           176.0   

      SuperplasticizerComponent  CoarseAggregateComponent  \
id                                                          
5407                        4.6                    1007.2   
5408                        0.0                     998.0   
5409                        0.0                    1113.0   
5410                        6.4                    1028.4   
5411                        6.0                    1021.0   

      FineAggregateComponent  AgeInDays  
id                                       
5407                   746.6         56  
5408                   801.0          7  
5409                   833.0         28  
5410                   757.7        100  
5411                   709.0         28

In [ ]:
f = open("test.csv", "w")

for i in range(len(predict_x_test)):
    f.write("{}\n".format(predict_x_test[i]))

f.close()

In [ ]:
test_df.drop('id', axis=1, inplace = True)

KeyError: ignored

In [ ]:
list_of_tuples = list(zip(test_df["AgeInDays"], predict_x_test))

In [ ]:
submission_df = pd.DataFrame("id": test_df["id"], "")

ValueError: ignored

In [ ]:
#predict best model
predict_x_test1 = model_05.predict(test_df)

In [ ]:
predict_x_test1[:5]

array([35.56357199, 27.71262496, 27.30423939, 38.76333361, 32.15514862])

In [ ]:
from sklearn.linear_model import ElasticNet

model_06 = ElasticNet(alpha=1.0, l1_ratio=0.5)
model_06.fit(X_train, y_train)


ElasticNet()

In [ ]:
predict_x_test2 = model_06.predict(X_test)

In [ ]:
predict_x_test2[:5]

array([26.18360994, 30.09891522, 40.18147123, 36.59324272, 33.07387015])

In [ ]:
y_test[:5]

id
4269    32.40
1615    18.20
1924    44.52
230     22.93
465     21.50
Name: Strength, dtype: float64

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline

degree = 2  # Choose the degree of the polynomial
model_07 = make_pipeline(PolynomialFeatures(degree), LinearRegression())
model_07.fit(X_train, y_train)

Pipeline(steps=[('polynomialfeatures', PolynomialFeatures()),
                ('linearregression', LinearRegression())])

In [ ]:
predict_x_test3 = model_07.predict(X_test)

In [ ]:
predict_x_test3[:5]

array([21.06988668, 27.01175159, 52.34494685, 39.44737758, 33.3549724 ])

In [ ]:
model_02.save("model12.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [ ]:
test_df = pd.read_csv("/content/test.csv",
                 parse_dates=["CementComponent"],
                 index_col=["CementComponent"]) # parse the id column (tell pandas column 1 is a id)
test_df.head()

id  BlastFurnaceSlag  FlyAshComponent  WaterComponent  \
CementComponent                                                            
166.1            5407              75.4            163.8           173.8   
304.0            5408               0.0              0.0           190.0   
225.0            5409               0.0              0.0           185.0   
251.4            5410               0.0            118.3           188.5   
144.0            5411              15.0            195.0           176.0   

                 SuperplasticizerComponent  CoarseAggregateComponent  \
CementComponent                                                        
166.1                                  4.6                    1007.2   
304.0                                  0.0                     998.0   
225.0                                  0.0                    1113.0   
251.4                                  6.4                    1028.4   
144.0                                  6.0                    1021.0   

                 FineAggregateComponent  AgeInDays  
CementComponent                                     
166.1                             746.6         56  
304.0                             801.0          7  
225.0                             833.0         28  
251.4                             757.7        100  
144.0                             709.0         28

In [ ]:
list_of_tuples = list(zip(test_df["id"], predict_x_test))

In [ ]:
df = pd.DataFrame(list_of_tuples,
                  columns=['id', 'Strength'])

In [ ]:
df.

id     Strength
0     5407  [44.296204]
1     5408  [21.586994]
2     5409  [32.879562]
3     5410  [46.112442]
4     5411  [31.608864]
...    ...          ...
3600  9007   [34.20232]
3601  9008  [34.960033]
3602  9009   [41.61788]
3603  9010  [48.193775]
3604  9011  [23.197773]

[3605 rows x 2 columns]

In [ ]:
df.to_csv('file1.csv')

In [16]:
import tensorflow as tf

In [18]:
from keras import layers

In [20]:
X_train

CementComponent  BlastFurnaceSlag  FlyAshComponent  WaterComponent  \
id                                                                         
5173            277.1               0.0             97.4           160.6   
3288            425.0             106.3              0.0           151.4   
1010            362.6             189.0              0.0           164.9   
1029            349.0               0.0              0.0           192.0   
4665            339.0               0.0              0.0           197.0   
...               ...               ...              ...             ...   
3772            350.0               0.0              0.0           186.0   
5191            250.2             166.8              0.0           185.7   
5226            540.0               0.0              0.0           173.2   
5390            500.0             153.0              0.0           200.0   
860             286.3             200.9              0.0           144.7   

      SuperplasticizerComponent  CoarseAggregateComponent  \
id                                                          
5173                       11.8                     973.9   
3288                       18.6                     936.0   
1010                       11.6                     944.7   
1029                        0.0                    1047.0   
4665                        0.0                     968.0   
...                         ...                       ...   
3772                        0.0                     974.0   
5191                        0.0                    1111.6   
5226                        0.0                    1125.0   
5390                        0.0                    1125.0   
860                        11.2                    1004.6   

      FineAggregateComponent  AgeInDays  
id                                       
5173                   875.6         28  
3288                   803.7          7  
1010                   755.8         91  
1029                   806.0          7  
4665                   781.0         28  
...                      ...        ...  
3772                   775.0         56  
5191                   784.3         28  
5226                   613.2          7  
5390                   613.0        180  
860                    803.7          7  

[4325 rows x 8 columns]

In [21]:

# Set random seed
tf.random.set_seed(42)

# Build the model (3 layers, 128, 10, 1 units)
# Let's build an LSTM model with the Functional API
inputs = layers.Input(shape=(8))
x = layers.Lambda(lambda x: tf.expand_dims(x, axis=1))(inputs) # expand input dimension to be compatible with LSTM
# print(x.shape)
# x = layers.LSTM(128, activation="relu", return_sequences=True)(x) # this layer will error if the inputs are not the right shape
x = layers.LSTM(128, activation="relu")(x) # using the tanh loss function results in a massive error
# print(x.shape)
# Add another optional dense layer (you could add more of these to see if they improve model performance)
# x = layers.Dense(32, activation="relu")(x)
output = layers.Dense(1)(x)
model_07 = tf.keras.Model(inputs=inputs, outputs=output, name="model_7_lstm")

# Compile the model
model_07.compile(loss=tf.keras.losses.mae,
                          optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
                          metrics=['mse'])

# Fit the model for 200 epochs (same as insurance_model_2)
model_07.fit(X_train, y_train, epochs=200, verbose=0)

In [23]:
# Load in best version of model 5 and evaluate on the test data
model_07.evaluate(X_test, y_test)

34/34 [==============================] - 1s 5ms/step - loss: 9.3040 - mse: 146.0580


[9.304010391235352, 146.05796813964844]

In [37]:
def build_model(hp):
      inputs = layers.Input(shape=(8))
      x = layers.Lambda(lambda x: tf.expand_dims(x, axis=1))(inputs) # expand input dimension to be compatible with LSTM
      # print(x.shape)
      # x = layers.LSTM(128, activation="relu", return_sequences=True)(x) # this layer will error if the inputs are not the right shape
      x = layers.LSTM(units=hp.Int('units', min_value=32, max_value=512, step=32), activation="relu")(x)
      x = layers.Dense(units=hp.Int('units', min_value=32, max_value=512, step=32), activation="relu")(x) # using the tanh loss function results in a massive error
      # print(x.shape)
      # Add another optional dense layer (you could add more of these to see if they improve model performance)
      # x = layers.Dense(32, activation="relu")(x)
      output = layers.Dense(1)(x)
      model_08 = tf.keras.Model(inputs=inputs, outputs=output, name="model_7_lstm")

      # Compile the model
      model_08.compile(loss=tf.keras.losses.mae,
                                optimizer=tf.keras.optimizers.Adam(learning_rate=hp.Choice('learning_rate', values=[1e-2, 1e-3, 1e-4])),
                                metrics=['mse'])
      return model_08

In [38]:
tuner = kt.RandomSearch(
    build_model,
    objective='val_mse',
    max_trials=50,
    directory='hyperparameter_tuning2',
    project_name='my_project'
)

tuner.search(X_train, y_train, epochs=10, validation_data=(X_train, y_train))

Trial 48 Complete [00h 00m 10s]
val_mse: 179.54150390625

Best val_mse So Far: 148.35995483398438
Total elapsed time: 00h 24m 11s


In [39]:
best_hps = tuner.get_best_hyperparameters(num_trials=1)[0]

In [40]:
model_07_best = tuner.hypermodel.build(best_hps)
model_07_best.fit(X_train, y_train, epochs=100, validation_data=(X_test, y_test))

Epoch 1/100
136/136 [==============================] - 5s 18ms/step - loss: 11.8138 - mse: 228.2643 - val_loss: 11.0851 - val_mse: 194.8898
Epoch 2/100
136/136 [==============================] - 2s 15ms/step - loss: 10.8059 - mse: 198.8206 - val_loss: 10.5752 - val_mse: 189.0329
Epoch 3/100
136/136 [==============================] - 2s 15ms/step - loss: 10.3574 - mse: 184.7857 - val_loss: 10.1293 - val_mse: 166.1559
Epoch 4/100
136/136 [==============================] - 2s 15ms/step - loss: 10.0178 - mse: 173.9787 - val_loss: 9.7637 - val_mse: 160.3319
Epoch 5/100
136/136 [==============================] - 2s 18ms/step - loss: 9.8262 - mse: 169.8365 - val_loss: 9.7994 - val_mse: 157.9823
Epoch 6/100
136/136 [==============================] - 3s 23ms/step - loss: 9.6958 - mse: 165.8954 - val_loss: 9.6813 - val_mse: 163.7125
Epoch 7/100
136/136 [==============================] - 2s 17ms/step - loss: 9.5215 - mse: 160.6259 - val_loss: 9.5867 - val_mse: 153.0385
Epoch 8/100
136/136 [======

In [41]:
model_07_best.evaluate(X_test, y_test)

34/34 [==============================] - 0s 4ms/step - loss: 9.3500 - mse: 148.9976


[9.350015640258789, 148.99755859375]